2020-07-17 15:06:04,490 ERROR: Exception on /user/dan [GET] [in c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\cs199dr\appdata\local\programs\python\python36\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Dev\FlaskMegaTutorial\app\routes.py", line 86, in user
    page = request.args.get('page', 1, type=init)
NameError: name 'init' is not defined
2020-07-17 15:06:59,744 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:47]
2020-07-17 15:08:20,090 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:47]
2020-07-20 13:10:58,432 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:18:24,606 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:22:31,194 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:29:59,146 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:39:47,894 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:42:17,646 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:51:51,242 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 13:53:41,263 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 15:00:44,649 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
2020-07-20 15:01:02,688 ERROR: Exception on /reset_password_request [GET] [in c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Dev\FlaskMegaTutorial\app\routes.py", line 180, in reset_password_request
    title='Reset Password', form=form)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Dev\FlaskMegaTutorial\app\templates\reset_password_request.html", line 14, in template
    <p>{{ form.submit() }}</p>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-07-20 15:01:41,035 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:50]
