2020-07-21 09:27:20,028 ERROR: Exception on /login [GET] [in c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Dev\FlaskMegaTutorial\app\routes.py", line 65, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Dev\FlaskMegaTutorial\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Dev\FlaskMegaTutorial\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Dev\FlaskMegaTutorial\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\dev\flaskmegatutorial\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2020-07-21 09:31:42,919 INFO: Microblog startup [in C:\Dev\FlaskMegaTutorial\app\__init__.py:52]
